[versions]
jdk = "11" # min for android
sdk-min = "14"
sdk-target = "33"
kotlin = "1.8.10"
android-plugin = "8.0.1"
androidx = "1.6.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "android-plugin" }

[libraries]
ktlint = "com.pinterest:ktlint:0.48.1"
material = { module = "com.google.android.material:material", version.ref = "androidx" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx" }
androidx-preference-ktx = "androidx.preference:preference-ktx:1.2.0"
androidx-viewpager2 = "androidx.viewpager2:viewpager2:1.0.0"
androidx-multidex = "androidx.multidex:multidex:2.0.1"
